### ISSUE TITLE
0.3.4 Doesn't work on Ubuntu 14.04

### ISSUE THREAD

**Issue by phideas** [Storj/driveshare-gui#45]
./DriveShare: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory

**Comment by rkfg** [comment]
It seems that amd64 version is actually i386. `file DriveShare` says 
```
DriveShare: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV),
dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.26,
BuildID[sha1]=826095c3c9010be4e2be9179937bc92535855c4d, stripped
```

**Comment by pallas1** [comment]
32 bit non-static binary: not a good choice, imho; especially if you didn't set the correct dependencies in the package.
Unlike windows, linux installs have all been 64 bit for many years now, no sense in making a 32 bit binary.

**Comment by winsvega** [comment]
I confirm this bug

**Comment by guyjames** [comment]
Yes, same here: DriveShare: ELF 32-bit LSB  executable, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.26, BuildID[sha1]=826095c3c9010be4e2be9179937bc92535855c4d, stripped

**Comment by gamedevsam** [comment]
I generated a 32 bit ubuntu executable through a VM, and I'm not sure I can get a 64 bit version up and running. I'll try when I have some time, but any help in this matter would be very appreciated.

**Comment by super3** [comment]
@phideas @rkfg @pallas1 @winsvega @guyjames There as been a major release. See if 0.4+ fixes your issues. For Linux I would just highly recommend pulling from master and following the instructions. Only 3 simple commands.

**Comment by phideas** [comment]
Latest DEB package still doesn't run on Ubuntu 14.04.
Leaving here the errors so you can iron out some bugs.
Next I'll try to install manually.

[6666:1210/001839:ERROR:browser_main_loop.cc(189)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'fs-jetpack'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/opt/DriveShare/resources/app.asar/lib/electron_boilerplate/window_state.js:8:15)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by gordonwritescode** [comment]
Thanks, looks as simple as a missing dependency during release bundling. Will resolve.

**Comment by cbbcbail** [comment]
Installing manually failed for me as well.

**Comment by guyjames** [comment]
I got it to work on ubuntu 14.04 by doing:
> Install NVM: 
`curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh | bash
> Download source:
`git clone https://github.com/Storj/driveshare-gui.git && cd driveshare-gui
> Install Node
`nvm install node
> Compile code:
`npm install
> Start program:
`npm start

Now it starts up and asks for a password (presumably means create one, but when I put one in and press Enter nothing happens... that's another issue though of course).

**Comment by gordonwritescode** [comment]
@guyjames the password it's asking for is your user password (needed for installing `dataserv-client` depencies via `apt`). I'll improve the language there.

**Comment by pallas1** [comment]
I don't think installing from source should use apt: what about the distributions not using that tool?
Dependencies should be listed in the documentation (INSTALL file) so the user knows what to do before compiling.
The compiled package just needs to list the dependencies inside itself.

**Comment by gordonwritescode** [comment]
Well let me be more clear: `apt` is used to install `python` and `python-pip` if they do not exist (which is unlikely on most GNU/Linux distributions). Then `pip` is used to install `dataserv-client`.

In any case, I'll include instructions for installing dependencies in the README. The debian package that is created for bundled release should certainly make use of the system's package management instead of the current method, but let's track that issue separately. For this specific issue, I'm only concerned with getting the bundled release *working* for debian-based systems.

**Comment by gordonwritescode** [comment]
@pallas1 another option that I think I prefer is to not provide a debian package at all, but instead provide a bash script in the repo that GNU/Linux users can `curl` or `wget`, and pipe to `sh` that will handle dependency installation and setup based on the distro.

This would greatly reduce the overhead of maintaining different packages for different distros and remove the need to handle dependency installation from within the application.

What do you think about something similar to that?

**Comment by pallas1** [comment]
I would leave the shell script installation as a last resort. Having a well made deb file will open doors to many distros and could even be included in some repositories, even the official ones when it's the right time. Add rpm and you've covered the most popular distros.
The shell script would need to be maintained and tailored for the various distributions, just like the package files. And it will need to have very careful error checking, or it'll risk to make a mess.
Personally I'm a bit concerned when I'm asked to run a shell script with root privileges, I usually just avoid the installation all together.

**Comment by littleskunk** [comment]
Thats a nice wish but at the moment not possible: https://github.com/atom/electron/blob/master/docs/tutorial/supported-platforms.md

**Comment by littleskunk** [comment]
Retest with debian 8.2 failed.

**Comment by gordonwritescode** [comment]
@littleskunk what failed? I am running Debian 8 as my primary.

**Comment by gordonwritescode** [comment]
@littleskunk, I am going to have to do this the correct way and abandon the method that was in place when I adopted this project and move all dependency setup to the Debian `control` file (like I admittedly should have done in the first place). 

There are just too many potential problems with trying to install dependencies through the app on first run. 

@pallas1 I'll try to have this resolved today.

**Comment by littleskunk** [comment]
Retest ok. I used a virtual box image with ubuntu 14.04. I generated a new binary and restored a old savepoint after the ubuntu installation. That way i had no npm or nodejs installed. 
Ubuntu software center installed driveshare-gui and i was able to start it, select a folder, see the free space and start farming. Everything fine. Well done :)

Fix will come with driveshare-gui 0.4.2.

**Comment by gordonwritescode** [comment]
@littleskunk awesome, great to hear! If you think it's good to go, can you go ahead and merge #100 into `develop`?

Side note, I opened an [issue](https://github.com/Storj/dataserv-client/issues/187) on `dataserv-client` to handle creating a proper debian package for that project, which would allow us to remove the `postinst` script that does `pip install` of dataserv-client, making both of these projects package The Debian Way™ and  allow us to publish them both the the Debian archive, letting users install with:

```
apt-get install driveshare
```

**Comment by IgorGanapolsky** [comment]
I am getting the same error on my Win 10 machine now.  Any solution for this?

**Comment by littleskunk** [comment]
Ubunto error on a windows 10 machine? Are you sure this is the right issue?

**Comment by IgorGanapolsky** [comment]
See screenshot.
![err](https://cloud.githubusercontent.com/assets/201209/13920340/e0c0a15c-ef48-11e5-8ea9-0623149a19a7.png)

**Comment by littleskunk** [comment]
Looks like you need some more help. If you use driveshare-gui on windows it will download and use dataserv-client binary. No need to upgrade it yourself and no need to install python. 

Please join slack: http://slack.storj.io/ channel test_group_b. You will find me there (slack user name skunk). Lets speak about the right installation process for your needs.
